### ISSUE TITLE
Conectar à rede dos turtlebots no lab, fora do horario das aulas.

### ISSUE THREAD

**Issue by zecastelo** [guilhermelawless/introduction-robotics#1]
Estivemos agora no lab para testar com os turtlebots mas não existe a rede usada durante a aula. Assumo que tenha sido uma rede criada e que não é permanente.

Como fazemos para nos conectar não existindo essa rede?

Agradecido,
José Castelo

**Comment by guilhermelawless** [comment]
Resolvido pessoalmente - basta ligar o router que está lá à corrente. Não é necessário WAN, apenas se quiserem internet no turtlebot.
