### ISSUE TITLE
Mini-Project 2: Ponto 1

### ISSUE THREAD

**Issue by VascoNunes** [guilhermelawless/introduction-robotics#10]
Boas Guilherme,

O professor ainda não deu nas teóricas nenhum dos métodos de path planning, por isso estamos um bocado perdidos sobre o que poderemos apresentar já esta quinta-feira.

Estive a ver uns vídeos e penso que poderia criar um Action Client Server que faz publish de quatro waypoints do mapa da sala à escolha e fazer com que o robô faça um loop visitando esses 4 waypoints.
Será uma boa ideia ou é isso que é suposto fazer no ponto 1 do mini-projecto? 

![image](https://user-images.githubusercontent.com/22856608/48412767-998d5d80-e73d-11e8-8cb3-3ff3885c2375.png)

Não tenho a certeza é de como implementar um desses path planning methods que estão especificados.
Tem de ser especificado no launch file do MOVE_BASE node? Nomeadamante no parâmetro do local planner?

![image](https://user-images.githubusercontent.com/22856608/48412983-1ddfe080-e73e-11e8-99de-42c525ed35a2.png)

P.S: Nuns videos que eu vi (do robot ignite academy), falam de um global planner mas no entanto neste launch file do turtlebot3 não existe, porquê?

**Comment by guilhermelawless** [comment]
Olá,

Pelo que sei, já foram dados alguns algoritmos de path planning nas teóricas. O que não foi dado foi o motion planning / guidance. Mas o ponto 1 já conseguem fazer.

Para esta aula, recomendo restringirem-se à teoria. Ir ao livro, ver conceitos, e descrever como vão planear o caminho. Se quiserem, posteriormente, referir como vão fazer isso em ROS.

Se o global planner não é especificado nessa launch file, então ele usa o default, ver aqui: http://wiki.ros.org/move_base

Entretanto, umas ligações para começar (depois da teoria):

- Guia para o navigation stack: https://github.com/zkytony/ROSNavigationGuide
- Tutorial para escrever um global path planner: http://wiki.ros.org/navigation/Tutorials/Writing%20A%20Global%20Path%20Planner%20As%20Plugin%20in%20ROS
