### ISSUE TITLE
Mini-Proj 1: Offset entre o mocap e o laser_frame do robô

### ISSUE THREAD

**Issue by VascoNunes** [guilhermelawless/introduction-robotics#11]
Temos um offset de 25 cm entre o mocap_baser_link e o laser_frame. Quando mudamos para o base_link diminui para 15 cm. O que é que suposto fazermos para deixar de ter este offset, ou seja, que frames é suposto usarmos ou transformações que temos de adicionar/alterar. Nós estamos a correr a transformada do script publish_initial_tf.py

**Comment by guilhermelawless** [comment]
Qual é o offset no início?

**Comment by joaobarbosa97** [comment]
Os offsets mencionados são os iniciais. No entanto, experimenteis com outras frames e a que me parece mais fiel, no momento inicial do bag é a base_scan com uma distancia inicial do mocap de pouco mais de 1cm

**Comment by guilhermelawless** [comment]
Esses offsets parecem muito grandes utilizando o amcl. Os meus erros não chegam nunca a 1cm.

Os passos que estou a seguir:

- `rosbag play fixed_slam_easy.bag --clock --pause`
- ```roslaunch turtlebot3_navigation turtlebot3_navigation.launch map_file:=`rospack find turtlebot3_datasets`/data/map.yaml```
- `publish_initial_tf.sh map`
- Iniciar a bag

O erro inicial é 2mm entre a **mocap_laser_link** e **base_scan**.

Fiz agora upload de um script que faz print do erro euclideano (2D). Está em milímetros.
