### ISSUE TITLE
Erro de compilação do global planner

### ISSUE THREAD

**Issue by VascoNunes** [guilhermelawless/introduction-robotics#13]
Boas,
Está-me a dar este erro estranho (deve ser sobre o costmap) quando tento compilar o planner que implementei de acordo com o tutorial:

**/opt/ros/kinetic/include/costmap_2d/observation.h:36:29: fatal error: pcl/point_types.h: No such file or directory**

![image](https://user-images.githubusercontent.com/22856608/48968627-18aa4d80-efea-11e8-858a-23b787c22f62.png)

No makefile simplesmente adicionei esta linha como estava no tutorial (pus o path todo):
**add_library(rdt_planner_lib /home/vasco/catkin_ws/src/proj2/src/rdt_planner.cpp)**

Por agora assim é como eu tenho o planner criado só para testar:
![image](https://user-images.githubusercontent.com/22856608/48968667-88203d00-efea-11e8-95da-1cade122a111.png)

Agora não percebo é o erro da primeira imagem acima, será que tenho de implementar alguma coisa no initialize_method? Segundo o tutorial do ros, deixaram aquilo em branco por isso não seria preciso, acho eu.

Obrigado desde já.

**Comment by VascoNunes** [comment]
[Update], ja consegui resolver esse problema, tive de adicionar "costmap_2d" no makefile da package.
No entanto, apos adicionar o plugin do planner, dá-me este erro quando lanço o move_base:

![image](https://user-images.githubusercontent.com/22856608/48969765-3af89700-effb-11e8-8412-edeed2538285.png)

Tenho o planner_plugin.xml assim:

![image](https://user-images.githubusercontent.com/22856608/48969789-7f843280-effb-11e8-8785-da4ebf0ba986.png)

**Comment by guilhermelawless** [comment]
Não tenho a certeza, mas a última tag está desalinhada, não sei se importa.
