### ISSUE TITLE
Erro no planner c++

### ISSUE THREAD

**Issue by VascoNunes** [guilhermelawless/introduction-robotics#14]
Boas, estamos a conseguir comunicar do c++ para o python e vice-versa, só que estamos com este erro estranho:

![image](https://user-images.githubusercontent.com/22856608/49150314-58cc4180-f304-11e8-9e38-41a22b3774b1.png)

Ele está de facto a calcular o path correctamente no python (lado esquerdo) e a mandar para o c++ (lado direito) como se pode comprovar, mas depois existe este erro da tf. Ao princípio pensei que fosse por não estar a definir a orientação das poses (apesar de ser irrelevante) mas mesmo metendo a orientação continua com o mesmo erro.
Porque será que isto acontece?

**Comment by guilhermelawless** [comment]
Algumas das mensagens do lado esquerdo não têm frame_id.
