### ISSUE TITLE
Comando para lançar o turtlebot3 no gazebo nao funciona

### ISSUE THREAD

**Issue by VascoNunes** [guilhermelawless/introduction-robotics#2]
Quando tentei lançar o comando roslaunch turtlebot3_gazebo turtlebot3_world.launch, o terminal queixa-se que o package não é um launch file name. Portanto suponho que a package turtlebot3_gazebo desapareceu, não sei como. 

Já procurei por este erro, e tentei instalar o turtlebot3 e o gazebo outra vez mas sem sucesso.

Alguma hint do que poderá ser o problema?
![screenshot from 2018-10-20 15-44-43](https://user-images.githubusercontent.com/22856608/47256925-29155880-d47f-11e8-8554-740a00cd0b58.png)

P.S: no entanto existe a pasta turtlebot3_gazebo dentro do turtlebot3_simulations, não sei se isso tem alguma coisa a ver

![screenshot from 2018-10-20 15-48-48](https://user-images.githubusercontent.com/22856608/47256958-a8a32780-d47f-11e8-850f-848b914eea06.png)

Obrigado desde já,
Vasco Nunes

**Comment by guilhermelawless** [comment]
Uma coisa a tentar é voltar a compilar o código:

1. `catkin_make clean` para limpar
2. `catkin_make` para voltar a compilar
3. `source ~/.bashrc`

Em princípio deve chegar.

**Comment by VascoNunes** [comment]
Continua a não dar infelizmente

**Comment by VascoNunes** [comment]
Já consegui afinal, obrigado pela ajuda!
