### ISSUE TITLE
Dúvida em relação à package gmapping

### ISSUE THREAD

**Issue by VascoNunes** [guilhermelawless/introduction-robotics#3]
No caso do gmapping, é necessário definirmos só as transformadas entre o laser_scan_frame e o base_scan ou temos de definir todas as transformadas através do joint_states?

No rviz está-nos a dar este erro:
![image](https://user-images.githubusercontent.com/22856608/47494527-c985c700-d849-11e8-82f2-d334eb9739ae.png)

Devemos preocupar-nos em ter o robot model sem erros nenhuns? Ou seja tratar das transformadas entre todas as frames do robô?

**Comment by guilhermelawless** [comment]
Mais do que o RobotModel, o problema está na TF (frames). Se usares o `rosrun tf2_tools view_frames.py` vais verificar que a frame `/map` (repara no rviz que essa é a tua fixed frame) não está ligada ao robô.

Assim, o rviz não sabe onde colocar o modelo, e o scan por exemplo.

O algoritmo de mapping faz broadcast de uma TF `map -> odom` para a TF tree ficar ligada.

Apenas precisam de dizer ao gmapping quais são as frames a usar. 

Parâmetros tirados da [wiki](http://wiki.ros.org/gmapping)

>~base_frame (string, default: "base_link")
   The frame attached to the mobile base. 
~map_frame (string, default: "map")
    The frame attached to the map. 
~odom_frame (string, default: "odom")
    The frame attached to the odometry system.
