### ISSUE TITLE
Mapping problem on the corridor

### ISSUE THREAD

**Issue by joaobarbosa97** [guilhermelawless/introduction-robotics#5]
We tried to generate some bags of the robot on the corridor of floor 5. However the WiFi connection for the IR-turtles network fails on the other side of the floor. Since there is no connection the recording of the bags is impossible.

**Comment by guilhermelawless** [comment]
Right, that makes sense. From my experience, you have two options.

The first option is to take the router with you, by getting a battery. You don't need the ethernet cable. There are also ways of having your laptop behave like a router but i've never done that.

------

The second option is cumbersome, but we can make ROS work only in localhost, so you can launch stuff, detach from the session, and come back later. Some steps:

Create a file inside turtlebot, home folder, called **set_local.sh** with the following:
```bash
export ROS_MASTER_URI=http://localhost:11311
export ROS_HOSTNAME=localhost
export ROS_IP=localhost
```

In the terminals that will run roscore or ROS nodes, first do `source ~/set_local.sh`. Now ROS will run **exclusively** locally, and you can't run any nodes or rviz outside of turtlebot3.

You can still SSH into turtlebot3, so what i suggest is:

- In your computer do `TURTLE`
- In the SSH do `byobu`
- Use Shift+F2, Ctrl+F2 to create new splits, then Shift + arrows to navigate them
- Launch everything you need (first `source ~/set_local.sh`), confirm it is running by checking topics
- Start a bag
- Shift+F6 to detach from the byobu session
- Go through the corridor, and when you arrive back the robot should connect automatically. Use `byobu` to go back to the same terminals, and finish the bag.

Let me know if you need help. An alternative we can do is setup a small corridor-like environment in the lab.
