### ISSUE TITLE
Problema a correr o ekf_localization

### ISSUE THREAD

**Issue by nfsfo1-iscteiulpt** [guilhermelawless/introduction-robotics#6]
Quando corro o ekf_localization.launch ele dá um erro de ICP did not converge, eu não estou a conseguir resolver isso, e não mostra nada no Rviz.
É alguma configuração que preciso de alterar?

**Comment by guilhermelawless** [comment]
Sim, é esse o trabalho. Há parâmetros na pasta config, outros no launch file e alguns hardcoded no source code.

Importa dizer que a partir do momento em que o filtro divergir, é difícil que volte a convergir, pois trata-se de um método iterativo e que começa na solução anterior.

**Comment by guilhermelawless** [comment]
@nfsfo1-iscteiulpt  fiz diversos updates ao ekf_localization, neste momento já deve conseguir convergir como está, perdendo-se a meio. Terão de mexer nos parâmetros. Basta "git pull" ou fazer download da última versão https://github.com/guilhermelawless/ekf_localization
