### ISSUE TITLE
Ekf

### ISSUE THREAD

**Issue by nfsfo1-iscteiulpt** [guilhermelawless/introduction-robotics#7]
Quando ligo o computador o ekf corre sem erros, mas se fechar e tentar correr novamente ele dá este erro:
![imagem](https://user-images.githubusercontent.com/32704340/47912271-f3fe0280-de8f-11e8-982e-5adc89320d3b.png)
e tenho que reiniciar o computador para conseguir correr outra vez. Alguma solução para isto?

**Comment by guilhermelawless** [comment]
Antes de mais, ver [isto](https://github.com/guilhermelawless/introduction-robotics/issues/6#issuecomment-435348014).

Não é necessário reiniciar. Aconselho a correr a rosbag num terminal à parte ( --pause dá jeito), assim como o rviz. Assim só o ekf_localization é lançado novamente sem estar a fechar o resto.
