### ISSUE TITLE
problema com o map_saver

### ISSUE THREAD

**Issue by joaobarbosa97** [guilhermelawless/introduction-robotics#8]
Não estou a conseguir correr o map_saver de modo a poder guardar o mapa criado pelo gmapping. 
Tenho quase a certeza de anteriormente ter conseguido executar o map_saver. 
O erro que estou a receber é o seguinte
![screenshot from 2018-11-02 11-44-32](https://user-images.githubusercontent.com/15888745/47913726-0b8bba00-de95-11e8-8a1b-c2e7a2cdf42f.png)

**Comment by guilhermelawless** [comment]
Ver se o nó existe com `ls -lha /opt/ros/kinetic/lib/map_server`  e se tem permissões de execução para user,group e others.

Tentar: `sudo apt install ros-kinetic-map-server --reinstall`
