### ISSUE TITLE
Duas tf trees separadas no dataset

### ISSUE THREAD

**Issue by joaobarbosa97** [guilhermelawless/introduction-robotics#9]
Criei um tf listener para a partir do topico tf saber a distancia entre o mocap_laser_link e o laser_frame do turtlebot no entanto não estou a conseguir ter essa informação pois eles não se encontram na mesma tf tree.
[frames.pdf](https://github.com/guilhermelawless/introduction-robotics/files/2572234/frames.pdf)

**Comment by guilhermelawless** [comment]
A solução é publicar a TF inicial de forma a essas frames coincidirem (apenas no início). O script que faz isso está no [turtlebot3_datasets](https://github.com/guilhermelawless/turtlebot3_datasets) e chama-se [publish_initial_tf.sh](https://github.com/guilhermelawless/turtlebot3_datasets/blob/master/scripts/publish_initial_tf.sh)

**Comment by joaobarbosa97** [comment]
Resolvi o problema, não se tratava do publish_initial_tf.sh mas sim de estar a correr o fixed_slam_easy.bag, quando corro o slam_easy.bag funciona bem
